### ISSUE TITLE
Bank App Crash

### ISSUE THREAD

**Issue by SavageKiller13** [MrCrayfish/MrCrayfishDeviceMod#108]
I was starting to create an app for the mod when I started messing around with the apps. The issue I found is when you go into transfer and put 10 9s for the input and click withdraw it crashes. One way to possibly fix it is to hardcode a limit to what you can input.

**Comment by MastefChief** [comment]
https://github.com/MrCrayfish/MrCrayfishDeviceMod/commit/04ef4e604408f9d23fa0169a1771fb8acae4cf39

**Comment by MastefChief** [comment]
https://github.com/MrCrayfish/MrCrayfishDeviceMod/commit/96f1c8eded6720ba4bce85bd101df855058e0a29
