### ISSUE TITLE
Some images on the web dont get downloaded by the Image component

### ISSUE THREAD

**Issue by lukas2005** [MrCrayfish/MrCrayfishDeviceMod#12]
Steps to replicate
1. create an app with an image component
2. use this url as an url string: 
http://yt3.ggpht.com/-AzEP6eQw3Nc/AAAAAAAAAAI/AAAAAAAAAAA/BKsMPLothZE/s88-c-k-no-mo-rj-c0xffffff/photo.jpg
3. launch your app in game

What is happening:
theres infinite spinning wheel of death instead of image

What shloud happen:
Image shloud show up

PS i can help you fix this if u want

**Comment by dhtdht020** [comment]
I Assume it's because you used a jpeg image.

**Comment by lukas2005** [comment]
what just because of that if its really the issue then i know how to fix this

**Comment by MrCrayfish** [comment]
@dhtdht020 JPEG images are fine. It's an issue with the server rejecting the request. If you can check your logs @lukas2005 it may point to the issue.

**Comment by MrCrayfish** [comment]
Any update on the issue @lukas2005?

**Comment by lukas2005** [comment]
nope i was waiting for you to try to figure out whats the cause of the proble,

**Comment by MrCrayfish** [comment]
Hopefully fixed in https://github.com/MrCrayfish/MrCrayfishDeviceMod/commit/52b60c17995705259fc61ecd9ac184c6bfc0d6b1
