### ISSUE TITLE
Placeholder Clipping in textfields

### ISSUE THREAD

**Issue by MastefChief** [MrCrayfish/MrCrayfishDeviceMod#121]
When putting a placeholder in a text field, if it goes beyond the width it goes to new line and doesnt continue in the first line.

`TextField fuelTextField = new TextField(5, 78, 162);`
            `fuelTextField.setPlaceholder("{id:\"minecraft:blaze_powder\",Count:1}");`
            `scrollableLayout.addComponent(fuelTextField);`
![screenshot_276](https://user-images.githubusercontent.com/10660965/40270020-34f9e368-5b54-11e8-9913-c48a0a627c15.png)

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/MrCrayfishDeviceMod/commit/efbe62af4e35b498a066b777bc4aa5a20343d29a
