### ISSUE TITLE
Installed apps doesn't get saved

### ISSUE THREAD

**Issue by OstenTV** [MrCrayfish/MrCrayfishDeviceMod#122]
When you install an app from the App Store, reopen the laptop, your apps disappear. This is on multiplayer, I have not tested it in singleplayer.

**Comment by JacksonPlayz** [comment]
Hackiest way of saving apps:
1. Install the apps you want to save
2. Open one of them.
3. Hold F3 + C for 10 seconds then release (or end task in Task Manager to force crash the game)
4. Join back onto the server and your apps should be saved.

NOTE: If you save GitWeb and try opening it, it will crash when you open it the first time. (Or whatever app you have opened when you crash the game, haven't tested it.)
