### ISSUE TITLE
Allowed apps + App Store

### ISSUE THREAD

**Issue by OstenTV** [MrCrayfish/MrCrayfishDeviceMod#123]
Apps that are installed client side, but not server side still show up in the App Store, even though they can't be installed.

**Comment by MrCrayfish** [comment]
Cheers for the report! I will get to it soon

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/MrCrayfishDeviceMod/commit/fb597a876243baa5e6075df0c0a589d67a0923f6
