### ISSUE TITLE
Would it be possible to create a standalone version of GitWeb?

### ISSUE THREAD

**Issue by MajickTek** [MrCrayfish/MrCrayfishDeviceMod#127]
E.g. Minecraft-less?

The concept is really interesting and I looked at the code for the sites (as well as the app itself). I don't think it should be that hard, but I'm just wondering if it has tech that is Minecraft-specific.

**Comment by Ocelot5836** [comment]
it's possible, all you have to do is remove the mc rendering code and replace it with nre lwjgl rendering

**Comment by MrCrayfish** [comment]
Yes it's possible, closing because this is not an issue with the Device Mod.

**Comment by MajickTek** [comment]
Alright. Thanks!
