### ISSUE TITLE
Contexts (from combo boxes) don't render mouse overs correctly

### ISSUE THREAD

**Issue by gh102003** [MrCrayfish/MrCrayfishDeviceMod#13]
![2017-10-26_09 44 51](https://user-images.githubusercontent.com/29987935/32043396-8a500e64-ba32-11e7-86d1-02c8843f3adc.png)

**Comment by MrCrayfish** [comment]
Thanks for the report! Will fix in the next release

**Comment by gh102003** [comment]
Source code: https://github.com/gh102003/ClockApp
