### ISSUE TITLE
Deleting Apps?

### ISSUE THREAD

**Issue by SuperLegoLuis** [MrCrayfish/MrCrayfishDeviceMod#130]
When exiting computer and going back in, deletes GitWeb:
![issue 3](https://user-images.githubusercontent.com/39528861/40376801-3546d0f2-5de7-11e8-89f4-83d26624414f.png)
![issue 3 5](https://user-images.githubusercontent.com/39528861/40376811-39d0e310-5de7-11e8-9abf-6b6b1b215819.png)

**Comment by SuperLegoLuis** [comment]
This is hosted on a server (Just saying in case)

**Comment by MastefChief** [comment]
#122
