### ISSUE TITLE
Lightswitch app crashing

### ISSUE THREAD

**Issue by RandomGuyBOII** [MrCrayfish/MrCrayfishDeviceMod#132]
pls fix this, light switch app not working!, I've use a controller, then connect it with the red cable (i forgot the name) then i connect the controller to my router with the Ethernet cable (idk if dis is right) then i connect my laptop to my router with the ethernet cable and when i click/open on lightswitch it crashes, like instantly, click then it just crashes, pls if i did anything wrong or is it because of me using the wrong forge version idk? or is it because i'm using it on a mac?, tell me pls!

REAL LIFE laptop Specs:
Macbook Pro (15-inch, late 2011
Processor : 2.2 Ghz Intel Core i7
RAM : 4 GB 1333 MHz DDR3
Graphics Card : Intel HD graphics 3000 384 MB
 
Forge Version: forge-1.12.2-14.23.3.2701

Mods i use: MrCrayFish's Furniture Mod
                    MrCrayFish's Device Mod
                    OptiFine_1.12.2_HD_U_D3
                    and the LightSwitch mod itself
Minecraft Ver: 1.12.2

**Comment by MastefChief** [comment]
Duplicate #126

**Comment by AlexCouch** [comment]
You're not gonna get a solution if you scream at him to do it. That's just ridiculous. Ever heard of patience? He's got things to do.

**Comment by RandomGuyBOII** [comment]
yeah sorry, i just want it so bad LOL

**Comment by EasyCanadianGamer** [comment]
you need to update the Light Switch Mod: https://mrcrayfish.com/mods?id=lightswitch
