### ISSUE TITLE
GitWeb Sites- How-To- Create Locally and/or GitHub 

### ISSUE THREAD

**Issue by Cdez** [MrCrayfish/MrCrayfishDeviceMod#134]
It would be great if you could create a tutorial on how to A. Create a GitWeb site, B. How to put it locally, and/or C. How to put it into the GitWeb Sites repo. I think that it would be a great thing to teach a little bit about how to do this, because a lot of people think that this fresh idea is cool, and this would keep people interested I think. You could do a video on this explaining how it works and such.
-Thanks,
Cdez.

**Comment by AlexCouch** [comment]
Lmao this isn't an issue to the project. This is a personal issue. You need to go into the MrCrayfish Discord Server instead.

**Comment by AlexCouch** [comment]
Issues are like bugs or glitches that need to be fixed.
