### ISSUE TITLE
The apps in the laptop crashes my game every time.

### ISSUE THREAD

**Issue by EasyCanadianGamer** [MrCrayfish/MrCrayfishDeviceMod#138]
Hi, Mr.crayfish, 

 

I tried to go on the Home security app or really any app on the laptop and than it crashes.

 

I put the crash report om paste bin: https://pastebin.com/vtNsWY4K

**Comment by TyrellPlayz** [comment]
Maybe post what version of the device mod you are using and the version of each app you have installed and maybe post the entire crash log not a little bit of it.

**Comment by EasyCanadianGamer** [comment]
The Version of the device mod is 0.4.1 and here is the whole crash report: https://pastebin.com/Z2tFuWbF

**Comment by EasyCanadianGamer** [comment]
also the light switch mod is 1.1.1 and the laser addon is 1.0

**Comment by EasyCanadianGamer** [comment]
hi
hello anyone here

**Comment by MrCrayfish** [comment]
Unrelated to Device Mod. The addons need updating

**Comment by EasyCanadianGamer** [comment]
thank you

**Comment by EasyCanadianGamer** [comment]
how do you update the addon

**Comment by MrCrayfish** [comment]
Download the latest version of Lightswitch here: https://mrcrayfish.com/mods?id=lightswitch

**Comment by EasyCanadianGamer** [comment]
I am talking about the laser addon

**Comment by EasyCanadianGamer** [comment]
I tried to look for updated version of the laser addon, but i did not find any update for the laser addon
