### ISSUE TITLE
Tooltips get cut out

### ISSUE THREAD

**Issue by Itay2805** [MrCrayfish/MrCrayfishDeviceMod#15]
Tooltips are getting cut out when they are outside of the window.

I assume this is because of the GL Scissor

![image](https://user-images.githubusercontent.com/10487821/32103263-4fa15d8a-bb28-11e7-87f7-6efee7af248f.png)

**Comment by gh102003** [comment]
This is a duplicate of #14, which was fixed on a stream.

**Comment by Itay2805** [comment]
Well, then it is not fixed in the latest release....

**Comment by MrCrayfish** [comment]
It's fixed in the latest revision but not released yet.
