### ISSUE TITLE
Laptops Stopped Working

### ISSUE THREAD

**Issue by Drabbermonkey62** [MrCrayfish/MrCrayfishDeviceMod#162]
My son plays minecraft and enjoys the Device and Furniture mods, however, we originally had the device mod for quite some time and then he wanted the furniture mod too.  I installed the furniture mod and then the device mod seemed to stop working (he would put down a laptop and it wouldn’t open etc).
I do not play minecraft so I don’t know much about it.  However, I have tried deleting minecraft and reinstalling it and then reinstalling the device mod only and it still did not work.  
Any advice?  Below are my system details.
System: iMac 10.13.6
Minecraft Latest Release is 1.13.2
Forge Version is 1.12.2-forge1.12.2-14.23.5.2768 (from the launcher)
In minecraft it lists Minecraft Forge14.23.5.2768
Forge Mod Loader 8.0.99.99
Minecraft Coder Pack 9.42
Looks like the device mod is MrCrayfish’s Device Mod 0.4.1 
And the Mr.CrayFish Furniture Mod 6.0.0
Any advice?

**Comment by MrCrayfish** [comment]
Crouch and right click laptop to open the lid then simply right click to open the GUI.

**Comment by Drabbermonkey62** [comment]
Thank you for the response.  However, when the device mod and furniture mod are active at the same time, the crouch and right click laptop does not work.  When I rename the furniture mod to be .OLD instead of .jar, it does not load and the device mod works just fine.   Is there a trick to making the Device Mod and the Furniture mod to work together in the same session?   Or can you not use both mods at the same time.

My iMAC has both the mod files in ~Library/Minecraft/Mods/
