### ISSUE TITLE
the laser addon crashing

### ISSUE THREAD

**Issue by foxy149** [MrCrayfish/MrCrayfishDeviceMod#179]
any time i enter the home security app it crashes i will post the crash report

**Comment by foxy149** [comment]
637985

**Comment by foxy149** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
  LittlePatchingLoader (LittleTiles_v1.5.0-pre199_34_mc1.12.2.jar)
  Techguns Core (techguns-1.12.2-2.0.2.0_pre3.2.jar)
  CreativePatchingLoader (CreativeCore_v1.10.16_mc1.12.2.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-92.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  FMLModule (mdxlib-3.0.0.26.jar)
Contact their authors BEFORE contacting forge

// Don't be sad. I'll do better next time, I promise!

Time: 7/11/20 12:53 PM
Description: Updating screen events

java.lang.AbstractMethodError
	at com.mrcrayfish.device.core.Window.init(Window.java:62)
	at com.mrcrayfish.device.core.Laptop.openApplication(Laptop.java:504)
	at com.mrcrayfish.device.core.Laptop.lambda$openApplication$4(Laptop.java:489)
	at com.mrcrayfish.device.core.Laptop$$Lambda$1087/1477898344.accept(Unknown Source)
	at java.util.Optional.ifPresent(Optional.java:159)
	at com.mrcrayfish.device.core.Laptop.openApplication(Laptop.java:489)
	at com.mrcrayfish.device.core.Laptop.openApplication(Laptop.java:482)
	at com.mrcrayfish.device.core.TaskBar.handleClick(TaskBar.java:156)
	at com.mrcrayfish.device.core.Laptop.func_73864_a(Laptop.java:309)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at com.mrcrayfish.device.core.Laptop.func_146274_d(Laptop.java:444)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.mrcrayfish.device.core.Window.init(Window.java:62)
	at com.mrcrayfish.device.core.Laptop.openApplication(Laptop.java:504)
	at com.mrcrayfish.device.core.Laptop.lambda$openApplication$4(Laptop.java:489)
	at com.mrcrayfish.device.core.Laptop$$Lambda$1087/1477898344.accept(Unknown Source)
	at java.util.Optional.ifPresent(Optional.java:159)
	at com.mrcrayfish.device.core.Laptop.openApplication(Laptop.java:489)
	at com.mrcrayfish.device.core.Laptop.openApplication(Laptop.java:482)
	at com.mrcrayfish.device.core.TaskBar.handleClick(TaskBar.java:156)
	at com.mrcrayfish.device.core.Laptop.func_73864_a(Laptop.java:309)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at com.mrcrayfish.device.core.Laptop.func_146274_d(Laptop.java:444)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)

-- Affected screen --
Details:
	Screen name: com.mrcrayfish.device.core.Laptop

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['artick__fox'/478, l='MpServer', x=-882.76, y=76.50, z=-198.86]]
	Chunk stats: MultiplayerChunkCache: 358, 358
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-262,64,-205), Chunk: (at 10,4,3 in -17,-13; contains blocks -272,0,-208 to -257,255,-193), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 22948 game time, 22948 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 144 total; [EntityRabbit['Rabbit'/512, l='MpServer', x=-956.13, y=70.00, z=-179.06], ZombieFarmer['Zombie Farmer'/1025, l='MpServer', x=-888.52, y=73.00, z=-220.81], Bandit['Bandit'/1027, l='MpServer', x=-887.82, y=74.00, z=-211.50], SkeletonSoldier['Skeleton Soldier'/1031, l='MpServer', x=-913.50, y=70.00, z=-152.50], EntityBat['Bat'/1288, l='MpServer', x=-883.11, y=22.65, z=-199.21], EntityItem['item.item.egg'/1289, l='MpServer', x=-840.90, y=69.00, z=-186.17], EntityBat['Bat'/1299, l='MpServer', x=-825.76, y=61.03, z=-132.25], EntityBat['Bat'/1301, l='MpServer', x=-804.50, y=51.99, z=-144.75], EntityPig['Pig'/790, l='MpServer', x=-810.62, y=70.00, z=-158.79], SkeletonSoldier['Skeleton Soldier'/1046, l='MpServer', x=-938.49, y=57.00, z=-161.27], EntityVillager['Villager'/536, l='MpServer', x=-880.42, y=72.00, z=-191.32], EntityRabbit['Rabbit'/537, l='MpServer', x=-911.20, y=71.00, z=-171.54], EntityPig['Pig'/795, l='MpServer', x=-841.49, y=69.00, z=-140.78], EntityRabbit['Rabbit'/540, l='MpServer', x=-893.88, y=70.00, z=-167.90], EntityPig['Pig'/541, l='MpServer', x=-890.35, y=72.00, z=-223.40], ZombieFarmer['Zombie Farmer'/1309, l='MpServer', x=-812.50, y=36.00, z=-167.50], EntityItem['item.item.shovelIron'/542, l='MpServer', x=-884.88, y=72.00, z=-202.56], EntityVillager['Villager'/543, l='MpServer', x=-904.60, y=73.00, z=-201.48], EntitySkeleton['Skeleton'/1311, l='MpServer', x=-944.50, y=63.00, z=-253.50], EntityPig['Pig'/800, l='MpServer', x=-805.68, y=72.00, z=-198.20], EntityCreeper['Creeper'/1056, l='MpServer', x=-874.42, y=71.00, z=-216.20], EntityVillager['Villager'/544, l='MpServer', x=-906.63, y=73.00, z=-203.76], EntityPig['Pig'/801, l='MpServer', x=-805.66, y=72.00, z=-199.50], EntityVillager['Villager'/545, l='MpServer', x=-902.31, y=73.00, z=-202.70], SkeletonSoldier['Skeleton Soldier'/1058, l='MpServer', x=-853.58, y=68.00, z=-187.72], EntityVillager['Villager'/546, l='MpServer', x=-901.53, y=73.00, z=-202.74], EntityPig['Pig'/802, l='MpServer', x=-804.50, y=71.00, z=-196.50], EntityVillager['Villager'/547, l='MpServer', x=-906.08, y=73.00, z=-202.46], EntityPig['Pig'/803, l='MpServer', x=-804.50, y=71.00, z=-196.50], EntitySheep['Sheep'/804, l='MpServer', x=-820.60, y=71.00, z=-187.41], EntitySkeleton['Skeleton'/1060, l='MpServer', x=-818.31, y=37.00, z=-167.49], EntityPig['Pig'/805, l='MpServer', x=-822.28, y=72.00, z=-191.35], EntitySpider['Spider'/1317, l='MpServer', x=-924.50, y=68.00, z=-252.50], EntitySheep['Sheep'/806, l='MpServer', x=-809.82, y=72.00, z=-182.29], EntityPig['Pig'/807, l='MpServer', x=-814.75, y=72.00, z=-182.37], EntityPig['Pig'/808, l='MpServer', x=-823.31, y=72.00, z=-189.27], EntityBat['Bat'/1320, l='MpServer', x=-820.81, y=61.18, z=-138.89], EntityBat['Bat'/1321, l='MpServer', x=-808.39, y=51.00, z=-164.25], EntityPig['Pig'/810, l='MpServer', x=-807.72, y=71.00, z=-191.50], EntityCreeper['Creeper'/1067, l='MpServer', x=-820.94, y=71.00, z=-127.90], EntityCreeper['Creeper'/1324, l='MpServer', x=-892.20, y=70.00, z=-158.45], EntityPig['Pig'/813, l='MpServer', x=-821.49, y=71.00, z=-223.78], SkeletonSoldier['Skeleton Soldier'/1326, l='MpServer', x=-840.50, y=59.00, z=-178.50], ZombieMiner['Zombie Miner'/1071, l='MpServer', x=-922.50, y=72.00, z=-156.50], EntitySpider['Spider'/816, l='MpServer', x=-808.50, y=70.00, z=-254.50], ZombieMiner['Zombie Miner'/1329, l='MpServer', x=-835.50, y=72.00, z=-139.50], EntityItemFrame['entity.ItemFrame.name'/562, l='MpServer', x=-879.97, y=74.50, z=-201.50], EntityPig['Pig'/818, l='MpServer', x=-817.27, y=71.00, z=-231.40], EntityItem['item.tile.dirt.default'/563, l='MpServer', x=-875.33, y=67.94, z=-202.82], EntityItem['item.item.sulphur'/564, l='MpServer', x=-876.88, y=68.94, z=-203.85], EntityPig['Pig'/820, l='MpServer', x=-807.50, y=72.00, z=-223.50], EntityItem['item.item.techguns.mibgun'/565, l='MpServer', x=-876.88, y=68.94, z=-204.57], EntityPig['Pig'/821, l='MpServer', x=-816.50, y=72.00, z=-194.50], ZombieSoldier['Zombie Soldier'/1333, l='MpServer', x=-850.50, y=24.00, z=-119.50], EntityItem['item.item.techguns.mibgun'/566, l='MpServer', x=-874.41, y=67.94, z=-202.39], EntityPig['Pig'/822, l='MpServer', x=-818.70, y=72.00, z=-194.30], EntityItem['item.item.techguns.alienblaster'/567, l='MpServer', x=-875.88, y=68.94, z=-205.88], EntityItem['item.item.techguns.alienblaster'/568, l='MpServer', x=-874.13, y=67.94, z=-203.04], EntityChicken['Chicken'/824, l='MpServer', x=-840.22, y=69.00, z=-186.49], EntityItem['item.item.techguns.revolver'/569, l='MpServer', x=-874.86, y=68.94, z=-206.88], EntitySheep['Sheep'/825, l='MpServer', x=-832.31, y=70.00, z=-183.52], EntityItem['item.item.techguns.revolver'/570, l='MpServer', x=-874.13, y=67.94, z=-201.45], EntitySheep['Sheep'/826, l='MpServer', x=-833.39, y=70.00, z=-183.40], EntityItem['item.item.seeds'/827, l='MpServer', x=-847.86, y=68.00, z=-185.95], EntityItem['item.item.techguns.rocket_nuke'/572, l='MpServer', x=-876.88, y=68.94, z=-204.47], EntityItem['item.item.techguns.rocket_high_velocity'/573, l='MpServer', x=-876.88, y=68.94, z=-204.23], EntityPig['Pig'/829, l='MpServer', x=-805.50, y=71.00, z=-227.50], EntityXPOrb['Experience Orb'/574, l='MpServer', x=-874.53, y=67.00, z=-204.36], EntityPig['Pig'/830, l='MpServer', x=-805.50, y=71.00, z=-224.50], EntityXPOrb['Experience Orb'/575, l='MpServer', x=-874.53, y=67.00, z=-204.36], EntityPig['Pig'/831, l='MpServer', x=-811.17, y=70.00, z=-232.77], EntityXPOrb['Experience Orb'/576, l='MpServer', x=-874.53, y=67.00, z=-204.36], EntityPig['Pig'/832, l='MpServer', x=-806.28, y=70.00, z=-231.77], EntityXPOrb['Experience Orb'/577, l='MpServer', x=-874.53, y=67.00, z=-204.36], EntityPig['Pig'/833, l='MpServer', x=-813.86, y=70.00, z=-233.62], ZombieFarmer['Zombie Farmer'/580, l='MpServer', x=-864.81, y=66.00, z=-210.56], EntityItem['item.item.techguns.mac10'/581, l='MpServer', x=-866.21, y=69.00, z=-186.57], EntityItem['item.item.techguns.mac10'/582, l='MpServer', x=-866.03, y=69.00, z=-186.98], EntityPig['Pig'/583, l='MpServer', x=-873.74, y=71.00, z=-240.19], EntityPig['Pig'/584, l='MpServer', x=-855.55, y=68.00, z=-250.55], EntityPig['Pig'/585, l='MpServer', x=-854.50, y=69.00, z=-252.50], EntityPig['Pig'/586, l='MpServer', x=-851.50, y=68.00, z=-253.33], EntityPig['Pig'/588, l='MpServer', x=-871.39, y=71.00, z=-224.48], EntityPig['Pig'/589, l='MpServer', x=-878.53, y=71.00, z=-236.33], SkeletonSoldier['Skeleton Soldier'/1357, l='MpServer', x=-861.50, y=45.00, z=-126.50], Bandit['Bandit'/1359, l='MpServer', x=-863.50, y=45.00, z=-127.50], EntityCreeper['Creeper'/1360, l='MpServer', x=-805.50, y=53.00, z=-131.50], ZombieFarmer['Zombie Farmer'/1370, l='MpServer', x=-806.50, y=53.00, z=-131.50], ZombieMiner['Zombie Miner'/1372, l='MpServer', x=-809.50, y=53.00, z=-130.50], ZombieSoldier['Zombie Soldier'/606, l='MpServer', x=-864.33, y=67.00, z=-168.50], ZombieMiner['Zombie Miner'/1374, l='MpServer', x=-806.50, y=53.00, z=-130.50], EntityMooshroom['Mooshroom'/610, l='MpServer', x=-863.48, y=69.00, z=-166.20], EntityItem['item.techguns.item.t1_miner_chestplate'/611, l='MpServer', x=-861.12, y=68.00, z=-170.07], PsychoSteve['Psycho Steve'/1381, l='MpServer', x=-854.50, y=12.00, z=-162.50], ZombieFarmer['Zombie Farmer'/1383, l='MpServer', x=-851.50, y=12.00, z=-160.50], ZombieFarmer['Zombie Farmer'/1385, l='MpServer', x=-852.50, y=12.00, z=-163.50], ZombieSoldier['Zombie Soldier'/1387, l='MpServer', x=-852.50, y=12.00, z=-162.50], EntityBat['Bat'/1394, l='MpServer', x=-903.84, y=15.11, z=-129.39], EntityBat['Bat'/1167, l='MpServer', x=-804.46, y=29.46, z=-190.62], EntityPig['Pig'/682, l='MpServer', x=-846.74, y=68.00, z=-254.35], EntityRabbit['Rabbit'/946, l='MpServer', x=-962.02, y=70.00, z=-175.46], EntityBat['Bat'/1208, l='MpServer', x=-827.25, y=42.76, z=-277.46], EntityBat['Bat'/1209, l='MpServer', x=-831.16, y=42.38, z=-273.39], EntitySkeleton['Skeleton'/974, l='MpServer', x=-825.50, y=35.00, z=-151.50], EntitySkeleton['Skeleton'/975, l='MpServer', x=-825.50, y=35.00, z=-148.50], ZombieFarmer['Zombie Farmer'/1235, l='MpServer', x=-836.55, y=70.00, z=-187.16], EntityXPOrb['Experience Orb'/479, l='MpServer', x=-829.85, y=68.00, z=-155.47], SkeletonSoldier['Skeleton Soldier'/1247, l='MpServer', x=-842.50, y=53.00, z=-120.50], EntityItem['item.item.porkchopRaw'/480, l='MpServer', x=-826.29, y=68.00, z=-148.91], SkeletonSoldier['Skeleton Soldier'/1249, l='MpServer', x=-841.50, y=53.00, z=-121.50], EntityRabbit['Rabbit'/482, l='MpServer', x=-953.50, y=68.00, z=-278.50], ZombieMiner['Zombie Miner'/995, l='MpServer', x=-907.49, y=72.00, z=-198.22], EntityRabbit['Rabbit'/483, l='MpServer', x=-954.50, y=67.00, z=-276.50], ZombieMiner['Zombie Miner'/1251, l='MpServer', x=-846.50, y=53.00, z=-122.50], EntityPig['Pig'/484, l='MpServer', x=-824.61, y=70.00, z=-170.18], EntityChicken['Chicken'/485, l='MpServer', x=-837.41, y=69.00, z=-180.69], ZombieMiner['Zombie Miner'/1253, l='MpServer', x=-845.50, y=53.00, z=-121.50], EntitySkeleton['Skeleton'/486, l='MpServer', x=-821.89, y=70.00, z=-163.38], ZombieMiner['Zombie Miner'/999, l='MpServer', x=-915.50, y=72.00, z=-180.50], EntityRabbit['Rabbit'/487, l='MpServer', x=-956.80, y=64.00, z=-266.47], EntityPlayerSP['artick__fox'/478, l='MpServer', x=-882.76, y=76.50, z=-198.86], EntityItem['item.item.wheat'/489, l='MpServer', x=-834.20, y=68.00, z=-157.14], EntityItem['item.techguns.item.t1_miner_chestplate'/490, l='MpServer', x=-833.90, y=68.00, z=-157.15], EntityBat['Bat'/1260, l='MpServer', x=-803.13, y=51.69, z=-154.75], EntityItem['item.item.porkchopRaw'/493, l='MpServer', x=-832.41, y=68.00, z=-157.73], EntityBat['Bat'/494, l='MpServer', x=-836.39, y=60.10, z=-170.75], EntityRabbit['Rabbit'/497, l='MpServer', x=-935.16, y=71.00, z=-120.63], SkeletonSoldier['Skeleton Soldier'/1010, l='MpServer', x=-871.50, y=70.00, z=-142.50], EntityXPOrb['Experience Orb'/499, l='MpServer', x=-917.74, y=72.00, z=-191.23], ZombieSoldier['Zombie Soldier'/1012, l='MpServer', x=-870.50, y=70.00, z=-142.50], ZombieFarmer['Zombie Farmer'/500, l='MpServer', x=-934.50, y=67.00, z=-171.50], EntityItem['item.item.rottenFlesh'/502, l='MpServer', x=-912.22, y=72.00, z=-194.48], ZombieFarmer['Zombie Farmer'/1270, l='MpServer', x=-805.50, y=28.00, z=-179.50], EntityXPOrb['Experience Orb'/503, l='MpServer', x=-913.01, y=72.00, z=-193.66], EntityXPOrb['Experience Orb'/504, l='MpServer', x=-915.13, y=72.00, z=-194.11], EntityZombieVillager['Zombie Villager'/1272, l='MpServer', x=-807.50, y=71.00, z=-226.50], EntityItem['item.item.sulphur'/507, l='MpServer', x=-915.38, y=69.00, z=-229.41], EntityXPOrb['Experience Orb'/508, l='MpServer', x=-916.20, y=69.00, z=-228.25], ZombieFarmer['Zombie Farmer'/1276, l='MpServer', x=-839.54, y=68.00, z=-246.20], EntityXPOrb['Experience Orb'/509, l='MpServer', x=-916.51, y=68.00, z=-230.89], EntityXPOrb['Experience Orb'/510, l='MpServer', x=-913.90, y=69.00, z=-228.25], ZombieFarmer['Zombie Farmer'/1278, l='MpServer', x=-845.50, y=67.00, z=-245.50], EntityXPOrb['Experience Orb'/511, l='MpServer', x=-916.41, y=68.00, z=-230.76], EntityPig['Pig'/767, l='MpServer', x=-810.88, y=72.00, z=-142.56]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 841365312 bytes (802 MB) / 1476395008 bytes (1408 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F5 24 mods loaded, 24 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                   | Version           | Source                                    | Signature                                |
	|:------ |:-------------------- |:----------------- |:----------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft            | 1.12.2            | minecraft.jar                             | None                                     |
	| LCHIJA | mcp                  | 9.42              | minecraft.jar                             | None                                     |
	| LCHIJA | FML                  | 8.0.99.99         | forge-1.12.2-14.23.5.2847.jar             | None                                     |
	| LCHIJA | forge                | 14.23.5.2847      | forge-1.12.2-14.23.5.2847.jar             | None                                     |
	| LCHIJA | creativecoredummy    | 1.0.0             | minecraft.jar                             | None                                     |
	| LCHIJA | littletilescore      | 1.0.0             | minecraft.jar                             | None                                     |
	| LCHIJA | foamfixcore          | 7.7.4             | minecraft.jar                             | None                                     |
	| LCHIJA | techguns_core        | 1.12.2-1.0        | minecraft.jar                             | None                                     |
	| LCHIJA | cdm                  | 0.4.1             | cdm-0.4.1-mc1.12.2.jar                    | None                                     |
	| LCHIJA | ctm                  | MC1.12.2-1.0.2.31 | CTM-MC1.12.2-1.0.2.31.jar                 | None                                     |
	| LCHIJA | jei                  | 4.15.0.293        | jei_1.12.2-4.15.0.293.jar                 | None                                     |
	| LCHIJA | chisel               | MC1.12.2-1.0.2.45 | Chisel-MC1.12.2-1.0.2.45.jar              | None                                     |
	| LCHIJA | chiselsandbits       | 14.33             | chiselsandbits-14.33.jar                  | None                                     |
	| LCHIJA | creativecore         | 1.10.0            | CreativeCore_v1.10.16_mc1.12.2.jar        | None                                     |
	| LCHIJA | foamfix              | 0.10.10-1.12.2    | foamfix-0.10.10-1.12.2.jar                | None                                     |
	| LCHIJA | lasers-addon         | 1.0.0             | lasers-addon-1.0-1.12.2.jar               | None                                     |
	| LCHIJA | littletiles          | 1.5.0             | LittleTiles_v1.5.0-pre199_34_mc1.12.2.jar | None                                     |
	| LCHIJA | mdxlib               | 3.0.0.26          | mdxlib-3.0.0.26.jar                       | None                                     |
	| LCHIJA | techguns             | 2.0.2.0           | techguns-1.12.2-2.0.2.0_pre3.2.jar        | None                                     |
	| LCHIJA | trackapi             | 1.2               | TrackAPI-1.2.jar                          | None                                     |
	| LCHIJA | immersiveengineering | 0.12-92           | ImmersiveEngineering-0.12-92.jar          | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| LCHIJA | industrialwires      | 1.7-36            | IndustrialWires-1.7-36.jar                | 7e11c175d1e24007afec7498a1616bef0000027d |
	| LCHIJA | llibrary             | 1.7.19            | llibrary-1.7.19-1.12.2.jar                | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | jurassicraft         | 2.1.23            | JurassiCraft-1.12.2-2.1.23.jar            | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
LittlePatchingLoader (LittleTiles_v1.5.0-pre199_34_mc1.12.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
Techguns Core (techguns-1.12.2-2.0.2.0_pre3.2.jar)
  techguns.core.TechgunsASMTransformer
CreativePatchingLoader (CreativeCore_v1.10.16_mc1.12.2.jar)
  
IELoadingPlugin (ImmersiveEngineering-core-0.12-92.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
FMLModule (mdxlib-3.0.0.26.jar)
  com.asx.mdx.AccessTransformer
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 750 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 391.35, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 6x AMD FX(tm)-6300 Six-Core Processor 
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 9
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 391.35
	OpenGlRenderer: GeForce GTX 750 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 6

**Comment by MrCrayfish** [comment]
I don't support this mod anymore
