### ISSUE TITLE
Pixel Painter: Crash

### ISSUE THREAD

**Issue by MinecraftDoodler** [MrCrayfish/MrCrayfishDeviceMod#2]
Pixel Painter doesn't save after leaving the laptop or even the app for that matter I think you know this, but now I have found after opening up Minecraft on the latest version of the Mod(Branch: Files) trying to open Pixel Painters causes the game to crash. The problem was not found when attempting in other worlds.

**Comment by lukas2005** [comment]
try on the master branch

**Comment by MrCrayfish** [comment]
Closing due to Pixel Painter now using files and saves correctly.
