### ISSUE TITLE
The brand new ColourSceme

### ISSUE THREAD

**Issue by Aregev2** [MrCrayfish/MrCrayfishDeviceMod#23]
When I exit the laptop the color I chose returns to default. When I remove the resetDefault() it saves the color but applies it to all of the laptops in the world or server.

Plz fix it in the next livestream
Aregev2

**Comment by MrCrayfish** [comment]
Don't report bugs on unfinished features.

**Comment by Aregev2** [comment]
Sry, I thought it should be like that
Plz don't kill me

**Comment by Aregev2** [comment]
Will you be able to fix it BTW?
