### ISSUE TITLE
Inconsistent method naming

### ISSUE THREAD

**Issue by jochembroekhoff** [MrCrayfish/MrCrayfishDeviceMod#24]
All methods and fields should follow a uniform spelling.

This is not the case.
Example:

component.Image has `setBorderColor(Color colour)`
but
component.TextArea has `setBorderColour(Color colour)`

**Comment by MrCrayfish** [comment]
Cleaned up in https://github.com/MrCrayfish/MrCrayfishDeviceMod/commit/3abfaac65e316f21eb2f429c11ddcc869c896318
