### ISSUE TITLE
Tool Tip won't hide on selected ButtonToggle

### ISSUE THREAD

**Issue by jochembroekhoff** [MrCrayfish/MrCrayfishDeviceMod#26]
Just as the title says, when there is a ButtonToggle with a Tool Tip set to it, the tooltip won't hide when the mouse leaves the button and the toggle button is selected.

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/MrCrayfishDeviceMod/commit/861a11b947ffe91862673e0a724e73fcc2241478
