### ISSUE TITLE
File Browser folder bug

### ISSUE THREAD

**Issue by OstenTV** [MrCrayfish/MrCrayfishDeviceMod#29]
Sometimes all folders will disappear and 3/10 times crashes your game.

Here is a short video to show you how it's done: https://youtu.be/H4asCyD4pn8
And in singleplayer: https://youtu.be/vmL7LuQSuUQ

To recreate this:
1. Plug in a flash drive
2. Create a folder tree, with several folders and files, on the flash drive.
3. open a folder deep inside the folder tree.
4. make the scrollbar appear, by creating a bunch of files.
5. select the same flash drive from the menu.
6. select files while scrolling up and down.
7. Go back 1 folder.

If nothing happens. Go back to the folder you were selecting files in. Continue 5, 6 and 7 until it "works".

[crash-2017-12-05_18.37.11-client.txt](https://github.com/MrCrayfish/MrCrayfishDeviceMod/files/1532356/crash-2017-12-05_18.37.11-client.txt)

**Comment by MrCrayfish** [comment]
Can't seem to replicate the issue. Is this still a problem in pre6?

**Comment by OstenTV** [comment]
yep. Just tested it on the server, and it still happens.

**Comment by OstenTV** [comment]
It looks like it crashes when you deselect the item after the folders went away.

Here is another crash report:
http://ftpp.ostentv.dk:8011/GitHub/Device-mod/%C2%A429/crash-2018-01-09_15.57.52-client.txt

And here is another video:
http://ftpp.ostentv.dk:8011/GitHub/Device-mod/%C2%A429/Desktop%2001.09.2018%20-%2015.57.23.03.mp4

**Comment by OstenTV** [comment]
It's fixed in 0.2.0.

**Comment by MrCrayfish** [comment]
Cheers for the update!
