### ISSUE TITLE
The Item lists are a bit weird

### ISSUE THREAD

**Issue by Ocelot5836** [MrCrayfish/MrCrayfishDeviceMod#31]
When I was developing, I discovered an odd bug. If you clear an item list and set it's contents again but the contents are less than it was before, the list will stay scrolled the way it was and won't display anything untill you scroll up. 

ex.
![image](https://user-images.githubusercontent.com/19599406/33646674-b053c28e-da05-11e7-8dd2-01cc0c3bbc19.png)

![image](https://user-images.githubusercontent.com/19599406/33646658-944648aa-da05-11e7-826c-1e7d27c50572.png)

You can see the list is lower than it should be even though the list won't let you scroll back down.

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/MrCrayfishDeviceMod/commit/1b9b7f220dfda8a270d223caad7dd91b581fb769
