### ISSUE TITLE
When replacing a laptop, the usb attached is missing

### ISSUE THREAD

**Issue by DrSkull20** [MrCrayfish/MrCrayfishDeviceMod#36]
Cray, when you﻿ insert the flash drive to the computer and break the computer u only get the computer and no flash drive item.

Insert the Flash Drive to the computer and break the computer.

**Comment by AwesomeCodePerson** [comment]
Just a suggestion, change the name. I was just about to report that bug.

**Comment by MrCrayfish** [comment]
This has been fixed now. Not sure what commit but it's fixed
