### ISSUE TITLE
Villager in bank app

### ISSUE THREAD

**Issue by MagmaCoder** [MrCrayfish/MrCrayfishDeviceMod#41]
With settings open, opening the bank over the top the villager has some visual glitches

**Comment by fabbe50** [comment]
![image](https://user-images.githubusercontent.com/8047187/34338149-0d5b17ec-e966-11e7-9a5c-eb7e3d29ca4f.png)
You mean this? If so that's a Minecraft issue.

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/MrCrayfishDeviceMod/commit/97d610aef32f4dcbde86f76a4775f66941a5ad4b
