### ISSUE TITLE
Pixel painter icon

### ISSUE THREAD

**Issue by MagmaCoder** [MrCrayfish/MrCrayfishDeviceMod#42]
when i open the pixel painter app, the icon isnt centered correctly
![2017-12-22_08 43 54](https://user-images.githubusercontent.com/30716007/34291449-39392184-e6f4-11e7-8b0b-10a9901de9a6.png)

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/MrCrayfishDeviceMod/commit/342ef47e4fda9b3a728a413b798c0b5878bf9485
