### ISSUE TITLE
Custom Paintings

### ISSUE THREAD

**Issue by RealMCoded** [MrCrayfish/MrCrayfishDeviceMod#43]
When You Break a Custom Painting (In Creative) It Drops the painting like your in survival mode.
 
Version: 0.2.0-pre5

**Comment by AwesomeCodePerson** [comment]
I think that is an intentional feature, just incase you get rid of the painting and don't know about CTRL+MiddleClick then you can get it back!

**Comment by RealMCoded** [comment]
And Ctrl+MiddleClick Doesn't Work On Paintings. it gives paper but when you place it's a transparent image (No Image)

**Comment by fabbe50** [comment]
Well, the transparency thing is an issue with forge I believe, Crayfish submitted a pull request that is currently under review: https://github.com/MinecraftForge/MinecraftForge/pull/4594#pullrequestreview-83966729

**Comment by MisterMelDev** [comment]
@MrCrayfish This should be closed, since there was a commit that fixed it.
