### ISSUE TITLE
Startup Crash

### ISSUE THREAD

**Issue by AwesomeCodePerson** [MrCrayfish/MrCrayfishDeviceMod#46]
Forge Version: 1.12.2 14.23.0.2491
Mod Version: 0.2.0-pre6
Other Mods: None

My game crashes when I attempt to start up the mod.
I have attached my crash report.

[crash-2017-12-27_17.06.39-client.txt](https://github.com/MrCrayfish/MrCrayfishDeviceMod/files/1588292/crash-2017-12-27_17.06.39-client.txt)

**Comment by lukas2005** [comment]
weird
its this line of code: https://github.com/MrCrayfish/MrCrayfishDeviceMod/blob/622395a29396244bc7e91078fa724d63e1b6e5cd/src/main/java/com/mrcrayfish/device/init/RegistrationHandler.java#L40

**Comment by MisterMelDev** [comment]
I'm pretty sure this happens when you use the JAR file found in the Discord, which shouldn't be used.
You should only use that file in a development environment. Use the JAR file on CurseForge

**Comment by AwesomeCodePerson** [comment]
Yeah I used the JAR on Discord. Closed.
