### ISSUE TITLE
Renamed (and non-renamed I think) blocks that can be colored reset to red.

### ISSUE THREAD

**Issue by JacksonPlayz** [MrCrayfish/MrCrayfishDeviceMod#50]
When I renamed a router and printer I placed it down and they changed back to red. This happened on the Device API Test server.

Steps to Reproduce:
Join a multiplayer server (may happen in singleplayer)
Take a colored block that is not red from the Device Mod and rename it.
Place it down
It changes to red.

Video (can't upload to github)
https://www.dropbox.com/s/nfgslmq96vwiuh6/bug.mp4?dl=0

**Comment by MrCrayfish** [comment]
This is just a block update issue, it actually is the correct colour just on client side its not updated correctly. I look into a fix for it.

**Comment by MrCrayfish** [comment]
Hopefully I fixed it in https://github.com/MrCrayfish/MrCrayfishDeviceMod/commit/0f3a575e115facdb7041b7f4ad4cf2c52606cb2e
