### ISSUE TITLE
Text Boxes don't scroll

### ISSUE THREAD

**Issue by Ocelot5836** [MrCrayfish/MrCrayfishDeviceMod#53]
Text boxes do not scroll if you set them to not editable and try to move the bar.

![image](https://user-images.githubusercontent.com/19599406/34635446-2d567410-f244-11e7-899d-b59959aa9a9e.png)
as you can see here...kinda
trust me it doesn't scroll when not editable.

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/MrCrayfishDeviceMod/commit/07da6357e808d7ccc2a5be9d0744abf62170ea00
