### ISSUE TITLE
Windows can be moved oddly...

### ISSUE THREAD

**Issue by Ocelot5836** [MrCrayfish/MrCrayfishDeviceMod#54]
When opening the small window to select routers, if you select a router and keep your mouse button pressed after you press the green checkmark to close the window, you can move the top application even if you aren't hovered over it at all.

![image](https://user-images.githubusercontent.com/19599406/34637420-7d7b08b2-f26b-11e7-8d60-cc9a80d4bac1.png)
I will be able to move it when the window closes. Trust me on this it's just hard to show here.

**Comment by MrCrayfish** [comment]
Great find. Will look into a fix!
