### ISSUE TITLE
Windows have a small rendering bug

### ISSUE THREAD

**Issue by Ocelot5836** [MrCrayfish/MrCrayfishDeviceMod#55]
When windows are simply there, the very bottom of the windows has 2 pixels for border instead of one.

![image](https://user-images.githubusercontent.com/19599406/34684193-23b3a5ec-f459-11e7-9e78-60e13451d314.png)

**Comment by Ocelot5836** [comment]
![image](https://user-images.githubusercontent.com/19599406/34698428-ecb2dc96-f48c-11e7-9159-e3c2bb85d706.png)


that shows it's not just my apps maybe?

**Comment by MrCrayfish** [comment]
Potentially a graphics card issue. Will look into resolving
