### ISSUE TITLE
Loads of issues

### ISSUE THREAD

**Issue by banana439monkey** [MrCrayfish/MrCrayfishDeviceMod#58]
1. In Bank, view account does not work.
2. The background does not actually save.
3. Save in Pixel Painter does not work.
4. With any object, it is still there when the block below it is removed.
5. I feel the chair should be gravity affected, because I consider it to be an entity. If the colour helps, lime.

I will continue to report bugs as I see them. I do not know if any of these has been fixed, but I just got up, downloaded the new version and haven't opened Minecraft yet.

**Comment by MrCrayfish** [comment]
1. Not implemented yet. This is not a bug.
2. It does work
3. It does work
4. Not necessarily a bug but an unimplemented feature
5. This would be a feature, not a bug.

**Comment by banana439monkey** [comment]
Okay to all
