### ISSUE TITLE
Static Abuse

### ISSUE THREAD

**Issue by MisterMelDev** [MrCrayfish/MrCrayfishDeviceMod#60]
In a lot of places in the mod, the 'static' keyword is abused (misused).
See these links for more information:
- https://stackoverflow.com/questions/1530353/in-what-situations-is-static-method-a-good-practice
- https://docs.oracle.com/javase/tutorial/java/javaOO/classvars.html

**Comment by MrCrayfish** [comment]
How so? The StackOverflow has a lot of "I think" type answers. I don't think that I'm misusing it in any way. I know the behaviour of static. If you can show me a "misused" piece of static, I'll explain my reasoning.

**Comment by MisterMelDev** [comment]
What is and is not static abuse is a opinion for the most part, but there are some conventions.
For example, take this piece of code:
`public static CommonProxy proxy;` (MrCrayfishDeviceMod.java, line 52)
This shouldn't really be a thing. What would be the proper way is to remove the "static" keyword. The proxy would still be getable, by using `MrCrayfishDeviceMod.instance.proxy`. I don't see any reason why "proxy" should be static.

**Comment by MrCrayfish** [comment]
Strange yes, but ```public static CommonProxy proxy;``` is an API design for Forge. Removing static will cause the game to crash on load.

**Comment by MisterMelDev** [comment]
Ah, sorry. I forgot about that. There are still places where static gets misused, for example in the ApplicationManager. Everything in there is static, which - I think - is no real reason for. 🧀

**Comment by MrCrayfish** [comment]
Well ```ApplicationManager``` is designed to be a stateless object, meaning that it doesn't have any instance fields except constants. It should also never be able to have an instance, extend anything or be subclassed. It's a single place for the mod to know what applications have been registered.

Turning it into a singleton pattern with lazy loading, for example, would allow there to be an instance of it. There is not a case I can think of when I needed an instance of ApplicationManager.

Here is some discussion I found about static methods vs singleton pattern.
https://stackoverflow.com/questions/519520/difference-between-static-class-and-singleton-pattern

**Comment by MisterMelDev** [comment]
Hmm, well yeah. That seems logical.

I'm going to close this for now, since this is mainly opion-based.
