### ISSUE TITLE
Endermail rendering bug

### ISSUE THREAD

**Issue by OstenTV** [MrCrayfish/MrCrayfishDeviceMod#64]
The character from pressing tab renders in Endermail.

Here is a picture:
http://ftpp.ostentv.dk:8011/GitHub/Device-mod/%2364/ead5d154be544d84fb23bc35aa1d8de7.png

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/MrCrayfishDeviceMod/commit/c24182f9b66cbd650558727b4a809034b2f70e40
