### ISSUE TITLE
Printer count bug

### ISSUE THREAD

**Issue by Norge100** [MrCrayfish/MrCrayfishDeviceMod#69]
http://prntscr.com/i0n9u3

When i added more printer max, that will show that. Maybe you should lower text or something?

**Comment by MrCrayfish** [comment]
How do you replicate this?

**Comment by Norge100** [comment]
http://prntscr.com/i0nfhp

In the config of course

**Comment by Norge100** [comment]
Can you fix it, or?

**Comment by MrCrayfish** [comment]
It's just an issue with the config. Some reason Forge's configuration is not taking into consideration the max and min value. I've set the paper limit to be 99 but Forge doesn't even check it even though it has the option to set a max value. It will be fixed soon, it's not a critical issue.

**Comment by Norge100** [comment]
Okay
