### ISSUE TITLE
Laptop (and all devices) rendering weird in Item Frame

### ISSUE THREAD

**Issue by AwesomeCodePerson** [MrCrayfish/MrCrayfishDeviceMod#73]
Title says it all.

Screenshot: https://imgur.com/a/qAVhV

Until this bug is fixed I can't live my dream of owning a Tech Shop in MC.

**Comment by fabbe50** [comment]
I've made a pull request to fix this here: #74

**Comment by AwesomeCodePerson** [comment]
Cool @fabbe50

**Comment by MrCrayfish** [comment]
Improved in https://github.com/MrCrayfish/MrCrayfishDeviceMod/commit/9deab57bb9d4238ad3e6103c852f04cca3485d92
