### ISSUE TITLE
In application market pixel painter's description is broken

### ISSUE THREAD

**Issue by EfsaneKraft** [MrCrayfish/MrCrayfishDeviceMod#81]
Hi there Cray! I found something about device mod. As you can see from title in application market pixel painter's desc is broken can you fix this?

![bug](https://user-images.githubusercontent.com/35929541/36641862-e1cacfa6-1a47-11e8-9944-9669d3438e39.png)

**Comment by Aregev2** [comment]
He hasn't implemented all of the app's descriptions, it's an easy fix and I guess he will do it soon

Aregev2
