### ISSUE TITLE
Light Blue Router Recipe Created Yellow Router

### ISSUE THREAD

**Issue by HauntedCorpse** [MrCrayfish/MrCrayfishDeviceMod#82]
![recipebug](https://user-images.githubusercontent.com/16520713/36645836-58ff9f70-1a34-11e8-914a-940374b778ff.png)

**Comment by JacksonPlayz** [comment]
In JEI it shows that as well. The light blue router also has the same recipe and every other device has the proper crafting.

**Comment by MrCrayfish** [comment]
Fixed
