### ISSUE TITLE
Minecraft Crashes in Bank Application

### ISSUE THREAD

**Issue by gradle22** [MrCrayfish/MrCrayfishDeviceMod#86]
When you enter a higher number than 2,147,483,647 into the number field in the bank application and click deposit or withdraw, the game crashes. 

Try
Catch
? 😛

**Comment by MrCrayfish** [comment]
Thank for report, will eventually fix

**Comment by Aregev2** [comment]
Integer limit,
Try catch shall work
Or change from int to long

**Comment by MrCrayfish** [comment]
Fixed
