### ISSUE TITLE
Image not rendering on first layout oppened

### ISSUE THREAD

**Issue by MastefChief** [MrCrayfish/MrCrayfishDeviceMod#88]
When adding an image to a layout which is the first to open when a app launches it just shows a loading spinner. Although when i go to another layout and back then the image renders. 

Video: [http://mastefchief.com/issues/2018-03-02%2011-38-59.mp4](http://mastefchief.com/issues/2018-03-02%2011-38-59.mp4)

Code: 
`private Image imageTest;`
`private static final ResourceLocation image1 = new ResourceLocation("intothemineframe:textures/app/banner/itm_app.png");`
`imageTest = new Image(5, 5 ,0, 0, 50, 50, image1);`
`itmMenuLayout.addComponent(imageTest);
`

**Comment by Aregev2** [comment]
What type is image1
A Url, res location?

That's very strange tho

**Comment by MastefChief** [comment]
@Aregev2  res location, ill update the issue with that. Thank you.
