### ISSUE TITLE
Button contentWidth with empty text, mispositions the icon

### ISSUE THREAD

**Issue by jochembroekhoff** [MrCrayfish/MrCrayfishDeviceMod#94]
When a Button's text is set to `""` (empty, non-null String), some additional contentWidth is added.
However, when the text is set to `null`, no additional contentWidth is added.
This results in an inconsistent rendering.

#### Situation 1 (incorrect)
1. Create a Button: `Button btn = new Button(5, 5, "");`.
2. Set an icon: `btn.setIcon(Icons.CHEVRON_DOWN);`.

#### Situation 2 (correct)
1. Create a Button: `Button btn = new Button(5, 5, "");`.
2. Set an icon: `btn.setIcon(Icons.CHEVRON_DOWN);`.
3. Set the text to null: `btn.setText(null);`.

#### What actually happend
In situation 1, the icon is placed a little bit too far to the left.

#### Expected result
The icon in situation 1 is placed identical to how it is placed in situation 2.

### Suggested fix
Extend the if statement in Button.java:230 with the following code:
```java
&& !text.isEmpty()
```

So the new line would look like this:
```java
if(iconResource != null && text != null && !text.isEmpty()) contentWidth += 3;
```

I've tested this fix for myself. In the case of situation 1, it makes it work like situation 2. I haven't tested it to more extent.

**Comment by MrCrayfish** [comment]
Cheers! Fixed in https://github.com/MrCrayfish/MrCrayfishDeviceMod/commit/24732cf13f55837de2af4d3e5a24fbefa91c45c2
